### ISSUE TITLE
Cannot select very high streaming

### ISSUE THREAD

**Issue by BobMcclaw** [SpotCompiled/SpotilifeC#16]
Cannot choose very high streaming in settings, max will let me choose high only with spotilife

**Comment by BobMcclaw** [comment]
ios 16

**Comment by benswolo** [comment]
very high cannot be selected because that is specified server-side. The highest bitrate you can get is 160 kbps, which is the "High" setting. This behavior occurs regardless of ios version. 

If you download an older version of spotify with spotilife injected, you'll notice that you are able to select the "very high" option. However, this is just a placebo, and doesn't actually change the bitrate of the stream.

**Comment by yodaluca23** [comment]
Answered above
