### ISSUE TITLE
No CarPlay and Apple Watch extensions

### ISSUE THREAD

**Issue by M4v3r1cK87** [SpotCompiled/SpotilifeC#26]
Hi,
I've an Apple Watch 8 with the latest WatchOS version (now 10.0.1) and in my car I use CarPlay function (my phone is an iPhone 13 with the latest iOS version -- now 17.0.2).

In both cases I cannot see the Spotify app (neither in the Watch nor in the CarPlay -- in wireless mode or with the cable is the same).
I install the SpotilifeC app trought the SideStore repo (using the https://tiny.one/SpotC repo); I've tried also the SpotC++ app but is the same.

If your patch uses the default Spotify app without any modification, why I cannot see the app in both Watch 8 and CarPlay? How I can include/use the app in this cases?

Thank you so much
BR,
Valerio

**Comment by yodaluca23** [comment]
> Hi,
> 
> I've an Apple Watch 8 with the latest WatchOS version (now 10.0.1) and in my car I use CarPlay function (my phone is an iPhone 13 with the latest iOS version -- now 17.0.2).
> 
> 
> 
> In both cases I cannot see the Spotify app (neither in the Watch nor in the CarPlay -- in wireless mode or with the cable is the same).
> 
> I install the SpotilifeC app trought the SideStore repo (using the https://tiny.one/SpotC repo); I've tried also the SpotC++ app but is the same.
> 
> 
> 
> If your patch uses the default Spotify app without any modification, why I cannot see the app in both Watch 8 and CarPlay? How I can include/use the app in this cases?
> 
> 
> 
> Thank you so much
> 
> BR,
> 
> Valerio

As of right now, it's impossible to dycrypt watch apps, because it only becomes decrypted on the watch itself, and we don't have any proper WatchOS jailbreaks, to allow us to do this, and in any case, the tweaks wouldn't work. You can install the AppStore Spotify app, and use that in the car and on your watch... As I recommended here as-well...

https://github.com/SpotCompiled/SpotC-Plus-Plus/issues/14
